language: python
python: 3.6
install: true

git:
  depth: false
  quiet: true

stages:
  - name: setup
    if: type IN (push, pull_request)
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: setup
      python: 3.6
      script: python extras/rabbitmq/purge.py
    - stage: tests
      python: 3.6
      before_script: pip install tox-travis
      script: tox
    - stage: tests
      services: docker
      before_script:
        - cd deploy
        - make bootstrap
        - sudo chown -R travis private
        - make up
        - make ps
      script:
        - cd ../tests
        - openssl enc -aes-256-cbc -d -in integration/dummy.sec.enc -out integration/dummy.sec -k ${TESTUSER_SSHKEY_PASSWORD}
        - chmod 400 integration/dummy.sec
        - rm -f integration/output.debug
        - bats integration || { cat integration/output.debug; exit 1; }

notifications:
  email: false
  slack:
    secure: eUyEWWvrFbzW+j+WKIOrHm7zeJ+6+o/WmI5cp1UYsOT9emxGE4kzW057cG9EV+sgKUdoYP1zSfCH0TLSOjY7otyqccqZH5WxDtiBSEXpkA8ID8jzQnX1VZWFn1vK+gWpER87VdLonVGt4db1lqE3Gm/uCbEqzrmfYjE1Hrk4PM8FfLQfD3+YBPUnWGSZKAPmdHAKh7IF9VQ6f1zaspijp/Sxa7Dk9F+Z4o2nsZ1woSyOVAwWLJhkvEafyEFfb/9tPMF1wtoXlLEzV1JDRzyjzbLGXQcpo6+Qx3+v7w6eRbriifOq2tByBfeI+RlWytwOgb+B/mfN0uFPbdg/Bgr//NMDrqwCnFQs7A2Dj287mQZI4YpRvh4Cneu3ReVGQKd9SJq28BliwXBBv3xyeFfGEbBOMNKb0VCsNjRuWITncf/qx3Vxn13VAYxcdA9EZpa1UzT6V94nlbLUq3twFKBJiDmpraYnI+JGFCZ32Xh8bySNqbEBe7TnqAG015c4pKKx++3IQJePfSPbRKzwWNAM5yG7RuVmud5fxfN+KdQz7vKfjOeaHKG4PScfhRT0zthtgmPG+m5eCprIbdFlacU3UyobLtxZd8wI9qJnGGvB3bHOsuaqpS2ymDWbd/n1aeryrcTkS/gPuwMvTs6S32pRf/orKqyLfnSZPeTcOevbzHw=
